server:
  port: 8080
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:postgresql://localhost/exif-system-db
    username: postgres
    password: example
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
