server:
  port: 8080
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:postgresql://db/postgres
    username: postgres
    password: example
  servlet:
    multipart:
      max-file-size: 10GB
      max-request-size: 10GB
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
